runChecks([
    ("TitleExtractor", titleExtractorChecks),
    ("Vault", vaultChecks),
    ("MetadataIndex", metadataIndexChecks),
    ("AppState", appStateChecks),
    ("PluginLoop", pluginLoopChecks),
    ("WordCounter", wordCounterChecks),
    ("Tokenizer", tokenizerChecks),
    ("Decoration", decorationChecks),
    ("Styler", stylerChecks),
    ("LinkTokenizer", linkTokenizerChecks),
    ("LinkStyler", linkStylerChecks),
    ("BlockTokenizer", blockTokenizerChecks),
    ("BlockStyler", blockStylerChecks),
    ("ListTaskTokenizer", listTaskTokenizerChecks),
    ("ListTaskStyler", listTaskStylerChecks),
    ("CodeBlockTokenizer", codeBlockTokenizerChecks),
    ("CodeBlockStyler", codeBlockStylerChecks),
])
